version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test-mission-control:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: |
            cd mission_control
            python -m unittest discover tests
          name: Test Mission Control
  build-and-test-gooeybot:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: |
            cd gooey
            python -m unittest discover tests
          name: Test GooeyBot
  code-lint:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python -m autopep8 . --diff --recursive --exit-code --global-config project.toml
          name: Lint

workflows:
  main:
    jobs:
      - build-and-test-bot
      - code-lint