version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test-bot:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python -m unittest discover gooey/tests/ 
          name: Test
  code-lint:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python -m autopep8 . --diff --recursive --exit-code --global-config project.toml
          name: Lint

workflows:
  main:
    jobs:
      - build-and-test-bot
      - code-lint